spring.application.name=mcp-shopping-list

#synchronous server for our requests and responses
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.name=shopping-list-mcp-server
spring.ai.mcp.server.version=1.0.0

#mcp uses standard input/output, not through http or rest APIs
spring.main.web-application-type=none

#log can interfere with the STDIO communication from the MCP Client and server
spring.main.banner-mode=off
logging.pattern.console=